Added case-sensitivity option for usernames
laravel/fortify pull request #485
Opened 2023-09-01 08:57 UTC by Radiergummi

**Why**  
Using Postgres (and possibly other DBMS), comparisons are case-sensitive as opposed to MySQL.  
This causes issues where users would enter e.g. _**T**aylor<span>@</span>laravel.com_ on logging in but registered with _**t**aylor<span>@</span>laravel.com_, and receive a bad credentials error. This bites _every single installation of Fortify using Postgres_.

By storing the usernames in lowercase, and converting them before passing it to user-defined authentication logic, this problem just disappears.

**Backwards compatibility**  
I took care to not break BC anywhere:
 - The option defaults to `true` for now, meaning usernames are case-sensitive by default. That way, nothing breaks for existing applications, including those with custom workarounds. It should probably be set to `false` in the next major revision.
 - The case change happens before the input is passed to user-defined actions (e.g. `CreateNewUser`), so no changes to existing implementations are required.
 - The new `CanonicalizeUsername` action can just be dropped in existing users' pipelines, if desired.

2023-09-01 09:00 UTC, driesvints requested changes
I'm not 100% sure if a setting is the right solution here but let's see what @taylorotwell says.

2023-09-01 09:01 UTC, driesvints commented on src/Http/Controllers/ProfileInformationController.php
> +use function config;
Can you also remove all `use function config` and `use function app` imports? They're not needed. Thanks

2023-09-01 09:01 UTC, Radiergummi commented on src/Actions/CanonicalizeUsername.php
> +
Dang, sorry. IDE inserts it automatically.

2023-09-01 09:05 UTC, Radiergummi commented
> I'm not 100% sure if a setting is the right solution here but let's see what @taylorotwell says.

I don't really see another option which doesn't interfere with existing applications, but I'm open for any suggestions!

2023-09-06 20:40 UTC, taylorotwell commented
Made a few changes.

Renamed configuration option to `lowercase_usernames`. Made default value in fallback config `false` (to preserve BC), but updated stub value to `true` so all *new* applications will get the more correct and expected behavior IMO of lowercasing the username.

2023-09-06 20:42 UTC, merged

2023-09-27 12:29 UTC, martinbean commented
This is an amazing PR, it’s something I have to deal with (and remember to deal with) in applications using Postgres. However, should the lower-casing not be done _before_ storing? Otherwise validations will fail.

For example, say I have `john.doe@example.com` in my `users` table. If I try and register with `John.Doe@example.com` then the validation is going to pass because it's different casing. But when the controller comes to actually insert the database record, Fortify is going to down-case the submitted value, and the database is going to throw a unique constraint error (if the column does indeed have a unique constraint).

2023-09-28 06:38 UTC, driesvints commented
@martinbean good question actually. Can you weigh in here @Radiergummi?

2023-09-28 07:41 UTC, Radiergummi commented
In the [`RegisteredUserController`](https://github.com/laravel/fortify/blob/b5743b04b07f5420e85665d978d15c7728e8dc03/src/Http/Controllers/RegisteredUserController.php#L56-L60), the given username should be lowercased if the setting is enabled:

```php
public function store(Request $request,
                          CreatesNewUsers $creator): RegisterResponse
{
    if (config('fortify.lowercase_usernames')) {
        $request->merge([
            Fortify::username() => Str::lower($request->{Fortify::username()}),
        ]);
    }

    event(new Registered($user = $creator->create($request->all())));

    $this->guard->login($user);
    return app(RegisterResponse::class);
}
```

The idea here is to pass the correctly cased value to any user creator implementation already present - that should work well, unless the implementation retrieves the value from the request via any other means or changes the formatting somehow (but I don't think that is very likely).

Have I overlooked something here? Does that error actually crop up?

2023-10-12 12:31 UTC, martinbean commented
/cc @driesvints

2023-10-12 22:28 UTC, martinbean commented
@Radiergummi No normalisation happens in the implementation: https://github.com/laravel/fortify/blob/b5743b04b07f5420e85665d978d15c7728e8dc03/stubs/CreateNewUser.php#L24-L30

So if I submit `John.Doe@example.com` then that will pass validation, even if the all-lowercase equivalent (`john.doe@example.com`) exists in the database.

2023-10-13 06:08 UTC, Radiergummi commented
@martinbean Ah, but we call `$request->merge()` *before* passing the request to the `CreateNewUser` class if lowercase usernames are enabled. This merges the request data in-place, and overrides the given username with its lowercase variant - so the implementation will only ever receive `john.doe@example.com` in your example.

2024-08-31 21:38 UTC, carlosmintfan commented on src/Actions/CanonicalizeUsername.php
> +
LOL, very cool!

2024-08-31 21:39 UTC, carlosmintfan commented on src/Actions/CanonicalizeUsername.php
> +
Which tool are you using to insert it?